#!/usr/bin/env bash
# This script is configureing your Nginx server
# Install nginx
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

# Permission
sudo chown -R $USER:$USER /var/

# Create html files
echo "Hello World" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/error404.html

# Variable assignment
new_page="https://www.youtube.com/watch?v=QH2-TGUlwu4"
file="/etc/nginx/sites-available/default"

# Add lines to the default file to configure redirection and 404 errors
sudo sed -i "/listen 80 default_server/a rewrite ^/redirect_me $new_page permanent;" $file
sudo sed -i "/listen 80 default_server/a error_page 404 /error404.html;" $file
sudo sed -i "/listen 80 default_server;/a add_header X-Served-By $HOSTNAME;" $file

# Restart server
sudo service nginx restart
