#!/usr/bin/env bash
# This script is fixing conexion to port 80 and stop web server
ln -fs /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
rm /run/nginx.pid
