#!/usr/bin/env bash
# This script is giving you information about the school file
FILENAME=school
if [ -e "$FILENAME" ]
then
    echo "$FILENAME file exists"
    if [ ! -s "$FILENAME" ]
    then
        echo "$FILENAME file is empty"
    else
        echo "$FILENAME file is not empty"
    fi
    if [ -f "$FILENAME" ]
    then
        echo "$FILENAME is a regular file"
    fi
else
    echo "$FILENAME file does not exist"
fi
