#!/usr/bin/env bash
# This script is confifuring the container so that Nginx is running as the nginx user
sudo su
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
chmod -R 777 /etc/nginx/
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
